#! /bin/bash
# /etc/init.d/camera

### BEGIN INIT INFO
# Provides:          camera
# Required-Start:    
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts camera for drone FPV.
### END INIT INFO



OUT_LOG=/dev/null
BIN=/opt/Deauther/app
PID_FILE=/run/deauther.pid
APP_NAME="Deauther"
INIT_FILE="/etc/init.d/deauther"

start() {
    pid_guard

    echo "Starting ${APP_NAME}"
    "${BIN}" \ 2>&1 | tee "${OUT_LOG}" | logger -t deauther &
    echo "${APP_NAME} Started"
}

pid_guard() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -1 "${PID_FILE}")

        if  [ -n "${pid}" ] && [ -e "/proc/${pid}" ]; then
            echo "${APP_NAME} is already running. please stop it first"
            exit 1
        fi

        echo "Removing stale pidfile..."
        rm "${PID_FILE}"
    fi
}

stop() {
    echo "Stopping ${APP_NAME}"

    if [ -f "${PID_FILE}" ]; then
        pid=$(head -1 "${PID_FILE}")

        if [ -z "$pid" ]; then
            echo "Unable to get pid from ${PID_FILE}"
            exit 1
        fi

        if [ -e "/proc/${pid}" ]; then
            echo "Killing ${PID_FILE}: ${pid} "
            kill "${pid}"
            sleep 2

            if [ -e "/proc/${pid}" ]; then
                echo "Timed Out"
            else
                echo "Stopped"
            fi
        else
            echo "Process ${pid} is not running"
        fi

        rm -f "${PID_FILE}"
    else
        echo "Pidfile ${PID_FILE} doesn't exist"
    fi
}

case "$1" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop && start
      ;;
    *)
      echo "Usage: ${INIT_FILE} {start|stop|restart}"
      exit 1
      ;;
    esac
exit 0