#! /bin/bash
sudo chown eric:eric -R /opt/DeautherUI
go build ../app.go

mv app ../.

cd /opt/DeautherUI
./app

#yes | sudo cp -i deauther /etc/init.d/
#sudo chmod +x /etc/init.d/deauther
#sudo update-rc.d deauther defaults
#sudo service deauther start
